
select_template_header() {
cat <<EOF
<%@Language=Vbscript CodePage=65001%>
<%
' code generated by: ${BASH_SOURCE}
Option Explicit
Response.Buffer=true
Response.Expires=-1
Session.codePage=65001
%>
<!--#include virtual='/GDCRM/library/sys_SystemCheck_S.asp' -->
<%
'****************************************************
'   使用標準的開窗模式 (Regular Dialog Window)
'****************************************************
dim lngPage

if Int(Request("gd_P")) > 0 then
    lngPage = clng(Request("gd_P"))
else
    lngPage = 1
end if

%>
<html>
<head>
<meta http-equiv='Content-Type' content='text/html;charset=utf-8'>
<meta http-equiv='Content-Language' content='<%=Session("s_Content")%>'>
<link href='/GDCRM/css/default.css' rel='stylesheet' type='text/css'>
<title>
	(<%=objKey.ReadResString("$(echo ${TEMPLATE}|tr [:lower:] [:upper:])",Session("s_Language"))%>)
	<%=objKey.ReadResString("QUICK_QUERY",Session("s_Language"))%>
</title>
<!--#include virtual='/GDCRM/library/sys_SelectScript_Constant.asp' -->
<script language='jscript.encode' src='/GDCRM/library/sys_SelectScript_C.js'></script>
<script language='jscript.encode'>
var g_strCurField = "fld1";
var g_strOrderType = "asc";
var g_intFieldNo = 1;
var g_lngPage = <%=lngPage%>;
var g_strFilter = escape("<%=Trim(Request("gd_FI"))%>");
var g_strWhere = escape("<%=Request("gd_W")%>");
var g_xmlHttp;
var g_xmlDoc = new ActiveXObject("Microsoft.XMLDOM");
var strXML = "";
var g_blnInit = false;

function Init() {
	document.all["blkHeader"].style.display = "none";
	var strURL = "/GDCRM/Library/${GD_ModuleID}/ws_List${TEMPLATE}_S.asp?gd_FI=" + g_strFilter + "&gd_W=" + g_strWhere + "&gd_P=" + g_lngPage + "&gd_O=" + g_strCurField.replace("fld","") + " " + g_strOrderType;
	//window.open(strURL);		//*** for debug
    g_xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");
	g_xmlHttp.open("GET", strURL, true);
	document.all["xmlData"].innerHTML = "XML Data " + g_msgLoading;
	g_xmlHttp.send();
	g_xmlHttp.onreadystatechange= Function( "LoadDataComplete();" );
}

function AfterLoadData() {
    document.all['txtValue'].focus();
}
function AfterInit() {
    g_blnInit = true;
}

</script>
</head>
EOF
}


select_template_optfield() {

#OW_SQL_FDS="DeptID/DEPT_ID DeptShortName/DEPT_SHORT_NAME DeptName/DEPT_NAME"

    if [ ! "$OW_SQL_FDS". = "". ] ; then
	for fd_pair in $OW_SQL_FDS ; do
	    fd_code=$( echo $fd_pair | sed 's|/.*$||g')
	    fd_res=$( echo $fd_pair | sed 's|^.*/||g')
cat <<EOF
		<option DataType='string' value='${fd_code}'>
			<%=objKey.ReadResString("${fd_res}",Session("s_Language"))%>
		</option>
EOF
	done
    fi

}

select_template_html() {
cat <<EOF
<body onload="Init();optFieldChange();" style='margin:2px'>
<div id='blkHeader' style='display:none'>
	<div>
		<%=objKey.ReadResString("SELECT_FILTER_FIELD",Session("s_Language"))%>：
		<select id='optField' onchange='jscript:optFieldChange();'>
EOF

select_template_optfield

cat <<EOF			
		</select>&nbsp;

		<select id='optOperator'></select>
		<br>
		<nobr>
		<%=objKey.ReadResString("INPUT_FIELD_VALUE",Session("s_Language"))%>:
		<input type='text' id='txtValue' value='' size='30' maxlength='30'
			onKeyPress='jscript:KeyPress();'>&nbsp;&nbsp;
		<button id='cmdQuery' class='clsButton2' style='height:20px' language='jscript'
			onmouseover='this.className="clsButtonOver2";' onmouseout='this.className="clsButton2";'
			onclick='jscript:Query();'>
			<%=objKey.ReadResString("START_QUERY",Session("s_Language"))%>
		</button>&nbsp;
		<button id='cmdClear' class='clsButton2' style='height:20px' language='jscript'
			onmouseover='this.className="clsButtonOver2";' onmouseout='this.className="clsButton2";'
			onclick='jscript:Clear();'>
			<%=objKey.ReadResString("CLEAR_CONDITION",Session("s_Language"))%>
		</button>
		</nobr>
	</div>
	<div id='Toolbar' class='clsToolbar2'></div>
</div>
<div id='xmlData'></div>
<p>&nbsp;</body>
</html>
EOF
}

_sys_SelectTemplate_asp() {
    select_template_header
    select_template_html
}
