#!/bin/bash
#
# FILE:  qemu.sh
# USAGE:  ./qemu.sh 
# DESCRIPTION:  launch qemu script
# AUTHOR:   (), 
# CREATED:  12/03/08 15:02:59    
# $Id: $
#
control_c()
{
    echo -en "\n*** Ouch! Exiting ***\n"
    exit $?
}

trap control_c SIGINT

help() {

	echo qemu launch script.
	echo ""
	echo raw help:	
	$QEMU_BIN/qemu --help
	echo ""
	echo usage: `basename $0` '[ --help | --audio? | --sound? | --M? | --cpu? | ImageFile ]'
	exit
}
#
source ~/opt/etc/qemurc
# ~/opt/etc/qemurc
# QEMU_BIN=/usr/src/qemu/qemu-20080810-window
# QEMU_HW=/usr/src/qemu/qemu-20080810-window
# EOF of ~/opt/etc/qemu.cfg
QEXE=qemu

if [ $# -eq 0 ] ; then
    help
fi

#echo $*
image=`echo $@ | tr ' ' '\n' | tail -n 1`
command=`echo $@ | tr ' ' '\n' | head -n 1`

#echo $command
case $command in
    --help)
	help
	;;
    --audio?)
	$QEMU_BIN/qemu -audio-help
	exit
	;;
    --sound?)
	$QEMU_BIN/qemu -soundhw ?
	exit
	;;
    --M?)
	$QEMU_BIN/qemu -M ?
	exit
	;;
    --cpu?)
	$QEMU_BIN/qemu -cpu ?
	exit
	;;
    --64)
	QEXE=qemu-system-x86_64
	shift
	;;
    *)
    ;;
esac
#echo $1
#echo $image

if test -a $image ; then
    filetype=`file -i $image`
    booted=`echo $filetype | grep -i iso9660 | wc -l`
    
    startpara=""
    if [ "$booted" -eq "1" ] ; then
	startpara="-cdrom"
    fi
    echo \'Start command is:\' $QEMU_BIN/qemu -L "`cygpath -w $QEMU_HW`" $startpara $*
    #sshchk $QEMU_BIN/qemu -L "`cygpath -w $QEMU_HW`" $startpara $*
    exec sshchk $QEMU_BIN/$QEXE -L "`cygpath -w $QEMU_HW`"  $*
    #echo return val: $?
    exit $?
else
    echo ERROR!!! Image file: \`$image\' not exist. qemu can\'t launch this image.
    exit 5
fi

#echo $@
