#!/bin/bash

# USAGE:  ./runvnc.sh host_name passwd 
# $Id: $
#

HOST_IP=`grep -i $1 /etc/hosts | grep -v '#' | gawk '{ print $1}'`

if [ "$HOST_IP". == "". ] ; then
    echo "Host name: $1 not exist in /etc/hosts."

    exit 1
else
    if [ "$2". == "". ] ; then
	echo "Empyt passwd is not allowed."
	exit 2
    else
	cygstart $HOME/PRGS/UltraVNC/vncviewer /password $2 $HOST_IP
    fi
fi
