

TOMCATPATH=`$TRANSPATH $CATALINA_HOME/common/lib/servlet.jar`
TOMCATPATH="$TOMCATPATH"';'`$TRANSPATH $CATALINA_HOME/common/lib/xerces.jar`

#TOMCATPATH="$TOMCATPATH"';'`$TRANSPATH $CATALINA_HOME/server/lib/catalina-ant.jar`
#TOMCATPATH="$TOMCATPATH"';'`$TRANSPATH $CATALINA_HOME/server/lib/`

CLASSPATH="$TOMCATPATH"';'"$CLASSPATH"

