choice_header() {
cat <<EOF
//generated by: ${BASH_SOURCE} 
//****************************************************
// g_msg${TEMPLATE}ID: 外部Global訊息變數
// g_msgCanNotBlank: 外部Global訊息變數
// g_msgChecking: 外部Global訊息變數
// g_msgMustBeExist${TEMPLATE}Id: 外部Global訊息變數
//
// g_aryHttpCaller: 外部Global變數
//
// sys_GetAyncCallerID(): 外部公用函數
// sys_Trim(): 外部公用函數
//
//*************************************************************************************************
// Version History:
//	init version: generated by ${BASH_SOURCE}
//*************************************************************************************************
// 開啟部門選擇視窗
EOF
}

choice_template() {
cat <<EOF
function sys_Choice${TEMPLATE}(srtMasterField,strDisplayField,strPostFunctionName,strWhere,strFilter) {
    try {
	    if (typeof(strWhere) == "undefined") { strWhere=""; }
		if (typeof(strFilter) == "undefined") { strFilter=""; }

		//*** 傳入的strWhere和strFilter 必須已經是經過escape()函數編碼。
		var strURL = "/GDCRM/Library/${GD_ModuleID}/sys_Select${TEMPLATE}.asp?gd_W=" + strWhere + "&gd_FI=" + strFilter;

		var aryRet = window.showModalDialog(strURL, null, 'dialogWidth:500px;dialogHeight:500px');
		if (typeof(aryRet) == "object") {
			document.all[srtMasterField].value = aryRet[0];			//aryRet[0]=部門代號
			document.all[strDisplayField].innerText = aryRet[1];	//aryRet[1]=部門簡稱
			eval(strPostFunctionName);
			try {sys_SetDataModified();} catch(e) {}
		}
    } catch(e) { alert("Error: sys_Choice${TEMPLATE}()\n" + e.description); }
}
EOF
}

check_templateID() {
cat <<EOF
// Check ${TEMPLATE} ID Code.
function sys_Check${TEMPLATE}ID(blnNotEmpty,strMasterField,strDisplayField,strPostFunctionName) {
	try {
	var strKeyValue = sys_Trim(document.all[strMasterField].value);
	if (strKeyValue == "") {
		document.all[strDisplayField].value = "";
		if (blnNotEmpty == true) {
			alert(g_msg${TEMPLATE}ID + g_msgCanNotBlank);
        }
		return;
	}

	var intCallerID = sys_GetAyncCallerID();
	if (intCallerID == -1) {return;}

	strKeyValue= strKeyValue.replace(/\'/g,"\'\'");

	//var strWhere = escape("DeptID LIKE N'%" + strKeyValue + "%'");
	var strWhere = escape("${TABLE_ID_VLAUE##} LIKE N'%" + strKeyValue + "%'");

	var strURL = "/GDCRM/Library/${GD_ModuleID}/ws_List${TEMPLATE}_S.asp?gd_FI=" + strWhere;

	var xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");
	xmlHttp.open("GET", strURL, true);
	g_aryHttpCaller[intCallerID] = xmlHttp;
	document.all[strDisplayField].value = g_msgChecking;
	xmlHttp.send();

	var strFunctionName = "sys_Check${TEMPLATE}ID_Finish(" + intCallerID + "," + blnNotEmpty + ",'" + strMasterField + "','" +
						  strDisplayField + "','" + strPostFunctionName + "');"
	xmlHttp.onreadystatechange= Function(strFunctionName);

    } catch(e) { alert("Error: sys_Check${TEMPLATE}ID()\n" + e.description); }
}
EOF
}

check_templateID_finish() {
cat <<EOF
function sys_Check${TEMPLATE}ID_Finish(intCallerID,blnNotEmpty,strMasterField,strDisplayField,strPostFunctionName) {
	try {
	var xmlHttp = g_aryHttpCaller[intCallerID];
	if (xmlHttp.readyState != 4) {
		return;
	}

	document.all[strDisplayField].value = "";
	g_aryHttpCaller[intCallerID] =  undefined;

	var strXML = xmlHttp.responseText;

	var xmlDoc = new ActiveXObject("Microsoft.XMLDOM");
	xmlDoc.async = false;
	xmlDoc.loadXML(strXML);
	if (xmlDoc.parseError.errorCode != 0 ) {
		alert(strXML);
		return;
	}

	var objNode = xmlDoc.documentElement.selectSingleNode("/Data/Recordset");
    if (objNode.childNodes.length == 0) {
        sys_ExpertCheck${TEMPLATE}ID(intCallerID,blnNotEmpty,strMasterField,strDisplayField,strPostFunctionName);
    }
    else {
        if (objNode.childNodes.length == 1) {
            //儲存傳回資料到 aryRet之中
            var aryRet = new Array();
            var objRecord = objNode.childNodes.item(0);
            for (var i=0; i< objRecord.childNodes.length; i++) {
                aryRet[i] = objRecord.childNodes.item(i).text;
            }
		    document.all[strMasterField].value = objNode.selectSingleNode("*/fld1").text;
		    document.all[strDisplayField].value = objNode.selectSingleNode("*/fld2").text;
		    eval(strPostFunctionName);
        }
        else {
            var strURL = "/GDCRM/Library/sys_ChoiceExpertDataDialog.asp";
            var aryRet = window.showModalDialog(strURL, xmlDoc, 'dialogWidth:500px;dialogHeight:400px');
            if (typeof(aryRet) == "object") {
                document.all[strMasterField].value = aryRet[0];
                document.all[strDisplayField].value = aryRet[1];
                eval(strPostFunctionName);
            }
            else {
		        document.all[strMasterField].value = "";
		        document.all[strDisplayField].value = "";
                if (blnNotEmpty == true) {
                    alert(g_msg${TEMPLATE}ID + g_msgCanNotBlank);
                }
		        return;
            }
        }
    }
    } catch(e) { alert("Error: sys_Check${TEMPLATE}ID_Finish()\n" + e.description); }
}
EOF
}

expertcheck_templateID() {
cat <<EOF
// Expert Check ${TEMPLATE} ID
function sys_ExpertCheck${TEMPLATE}ID(intCallerID,blnNotEmpty,strMasterField,strDisplayField,strPostFunctionName) {
try {
    var strKeyValue = sys_Trim(document.all[strMasterField].value);

	var strWhere = escape(" DeptShortName" + g_Language + " LIKE N'%" + strKeyValue + "%' OR DeptName" + g_Language + " LIKE N'%" + strKeyValue + "%' ");
    var strURL = "/GDCRM/Library/${GD_ModuleID}/ws_List${TEMPLATE}_S.asp?gd_W=" + strWhere;

    var intCallerID = sys_GetAyncCallerID();
    if (intCallerID == -1) {return;}

    var xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");
    xmlHttp.open("GET", strURL, true);
    g_aryHttpCaller[intCallerID] = xmlHttp;
    document.all[strDisplayField].value = g_msgChecking;
    xmlHttp.send();
    var strFunctionName = "sys_ExpertCheck${TEMPLATE}ID_Finish(" + intCallerID + "," + blnNotEmpty + ",'" +
                          strMasterField + "','" + strDisplayField + "','" + strPostFunctionName + "');";

    xmlHttp.onreadystatechange= Function(strFunctionName);
    } catch(e) { alert("Error: sys_ExpertCheck${TEMPLATE}ID()\n" + e.description); }
}
function sys_ExpertCheck${TEMPLATE}ID_Finish(intCallerID, blnNotEmpty, strMasterField, strDisplayField, strPostFunctionName) {
try {
    var xmlHttp = g_aryHttpCaller[intCallerID];
    if (xmlHttp.readyState != 4) {
        return;
    }
    document.all[strDisplayField].value = "";
    g_aryHttpCaller[intCallerID] =  undefined;

    var xmlDoc = new ActiveXObject("Microsoft.XMLDOM");
    xmlDoc.async = false;
    xmlDoc.loadXML(xmlHttp.responseText);
    if (xmlDoc.parseError.errorCode != 0) {
        alert(xmlHttp.responseText);
        return;
    }

    //ShowData
    var objDataNodes,objDataNode;
    var strTemp;

    objDataNodes = xmlDoc.documentElement.selectSingleNode("/Data/Recordset").childNodes;

    if (objDataNodes.length == 0) {
        alert(g_msgFoundNoData);
        document.all[strMasterField].value = "";
        document.all[strDisplayField].value = "";
        if (blnNotEmpty == true) {
            alert(g_msg${TEMPLATE}ID + g_msgCanNotBlank);
        }
        return;
    }

    if (objDataNodes.length == 1) {
        objDataNode = objDataNodes.item(0);
        //儲存傳回資料到 aryRet之中
        var aryRet = new Array();
        for (var i=0; i< objDataNode.childNodes.length; i++) {
            aryRet[i] = objDataNode.childNodes.item(i).text;
        }
        document.all[strMasterField].value = objDataNode.selectSingleNode("fld1").text;
        document.all[strDisplayField].value = objDataNode.selectSingleNode("fld2").text;
        eval(strPostFunctionName);
    }
    else {
        var strURL = "/GDCRM/Library/sys_ChoiceExpertDataDialog.asp";
        var aryRet = window.showModalDialog(strURL, xmlDoc, 'dialogWidth:500px;dialogHeight:400px');
        if (typeof(aryRet) == "object") {
            document.all[strMasterField].value = aryRet[0];
            document.all[strDisplayField].value = aryRet[1];
            eval(strPostFunctionName);
        }
        else {
            document.all[strMasterField].value = "";
            document.all[strDisplayField].value = "";
            if (blnNotEmpty == true) {
                alert(g_msg${TEMPLATE}ID + g_msgCanNotBlank);
            }
        }
    }
    } catch(e) { alert("Error: sys_ExpertCheck${TEMPLATE}ID_Finish()\n" + e.description); }
}
EOF
}

openedit_template_window() {
cat <<EOF
//OpenEdit ${TEMPLATE} Window
function sys_OpenEdit${TEMPLATE}Window(strFieldName) {
	try {
	var strKeyValue = sys_Trim(document.all[strFieldName].value);
	if (strKeyValue == "") return;
	window.open("/GDCRM/Prog/${TEMPLATE}/${TEMPLATE}_Modify.asp?gd_Key=" + strKeyValue);
    } catch(e) { alert("Error: sys_OpenEdit${TEMPLATE}Window()\n" + e.description); }
}
EOF
}

_sys_ChoiceTemplate_C_js() {
    choice_header
    choice_template
    check_templateID
    check_templateID_finish
    expertcheck_templateID
    openedit_template_window
}
