ws_list_header() {
cat <<EOF    
<%@Language=Vbscript CodePage=65001%>
<%
'Code generated by: ${BASH_SOURCE}
Option Explicit
Response.Buffer=true
Response.Expires=-1
Session.codePage=65001
%>
<!--#include virtual='/GDCRM/library/sys_SystemCheck_S.asp' -->
EOF
}

ws_list_page_size() {
cat <<EOF
<%
'檢查是否有指定要顯示的頁數
dim lngPage
if clng(Request("gd_P")) > 0 then
    lngPage = clng(Request("gd_P"))
else
    lngPage = clng(1)
end if

'設定開窗元件的分頁大小
dim intPageSize
intPageSize = 20
EOF
}

ws_list_SQL_fds() {

#OW_SQL_FDS="DeptID/DEPT_ID DeptShortName/DEPT_SHORT_NAME DeptName/DEPT_NAME"

    if [ ! "$OW_SQL_FDS". = "". ] ; then
	echo -n \"
	local first=1
	for fd_pair in $OW_SQL_FDS ; do
	    fd_code=$( echo $fd_pair | sed 's|/.*$||g')
	    if [ $first -eq 2 ] ; then  echo -n ", "; fi
	    echo -n $fd_code
	    first=2
	done
	echo -n "    \""
    else
	echo 1>&2 'Must define $OW_SQL_FDS when OpenWin code.'
    fi

}
ws_list_XML_fds() {

#OW_SQL_FDS="DeptID/DEPT_ID DeptShortName/DEPT_SHORT_NAME DeptName/DEPT_NAME"

local i=1
    if [ ! "$OW_SQL_FDS". = "". ] ; then
	for fd_pair in $OW_SQL_FDS ; do
	    fd_code=$( echo $fd_pair | sed 's|/.*$||g')
	    fd_res=$( echo $fd_pair | sed 's|^.*/||g')
cat <<EOF
strXML = strXML & "  <Field>" & vbcrlf
strXML = strXML & "    <Name>fld${i}</Name>" & vbcrlf
strXML = strXML & "    <Title>" & objKey.ReadResString("${fd_res}",Session("s_Language")) & "</Title>" & vbcrlf
strXML = strXML & "  </Field>" & vbcrlf

EOF
	    i=$(expr $i + 1)
	done
    fi

}

ws_list_SQL() {
cat <<EOF
'產生查詢的主要 SQL Command。
'注意：(1).語言別不同的欄位，不需要轉換欄位代號的Alias
'      (2).SQL指令中的欄位順序，必須與顯示的順序相符合。
'      (3).如果有隱藏不顯示的欄位(可以有多個)，請放在最後面。參考 ws_ListDept_S.asp

dim strSQL '暫存之SQL命令字串
strSQL = "SELECT	" & $(ws_list_SQL_fds) & _
         "FROM		${TEMPLATE} " & _
EOF

    if [ "${OW_SQL_WHERE}". = "" ] ; then
	echo -n '""'
    else
	echo -n -e \\t \""WHERE $OW_SQL_WHERE"\"
    fi
    echo ""

cat <<EOF
'檢查是否有傳入過濾條件(Filter)，例如，當開窗元件為查詢行業別時，很可能必要限定只能查詢某個產業別的行業
if trim(Request("gd_FI")) <> "" then
    strSQL = strSQL & " AND (" & Request("gd_FI") & ") "
    '檢查是否有查詢資料的Where條件
    if trim(Request("gd_W")) <> "" then
        strSQL = strSQL & " AND (" & Request("gd_W") & ") "
    end if
else
    '檢查是否有查詢資料的Where條件
    if trim(Request("gd_W")) <> "" then
        strSQL = strSQL & " AND (" & Request("gd_W") & ") "
    end if
end if

'將查詢的SQL子句加上ORDER BY
if trim(Request("gd_O")) = "" then
	strSQL = strSQL & " ORDER BY ${OW_SQL_ORDER_BY}"
else
	strSQL = strSQL & " ORDER BY " & trim(Request("gd_O"))
end if

'MyDebug strSQL

'產生 rstTemp 資料集
dim rstTemp     '暫存之Recordset
set rstTemp = objPublic.CreateRecordset(strSQL,Application("a_CRMConnect"))
EOF
}
ws_list_XML() {
cat <<EOF
'開始產生XML資料檔的表頭
'注意：這裡所列出的每一個 Field ，都是要顯示的欄位。隱藏的欄位不可以包含在 /Data/Fields/* 之中。
dim strXML
strXML = "<?xml version='1.0' encoding='utf-8' ?>" & vbcrlf
strXML = strXML & "<Data>" & vbcrlf
strXML = strXML & "<Fields>" & vbcrlf
EOF

ws_list_XML_fds

#strXML = strXML & "  <Field>" & vbcrlf
#strXML = strXML & "    <Name>fld1</Name>" & vbcrlf
#strXML = strXML & "    <Title>" & objKey.ReadResString("DEPT_ID",Session("s_Language")) & "</Title>" & vbcrlf
#strXML = strXML & "  </Field>" & vbcrlf

#strXML = strXML & "  <Field>" & vbcrlf
#strXML = strXML & "    <Name>fld2</Name>" & vbcrlf
#strXML = strXML & "    <Title>" & objKey.ReadResString("DEPT_SHORT_NAME",Session("s_Language"),Session("s_Language")) & "</Title>" & vbcrlf
#strXML = strXML & "  </Field>" & vbcrlf

#strXML = strXML & "  <Field>" & vbcrlf
#strXML = strXML & "    <Name>fld3</Name>" & vbcrlf
#strXML = strXML & "    <Title>" & objKey.ReadResString("DEPT_NAME",Session("s_Language"),Session("s_Language")) & "</Title>" & vbcrlf
#strXML = strXML & "  </Field>" & vbcrlf

cat <<EOF
strXML = strXML & "</Fields>" & vbcrlf

'檢查是否有找到資料
if rstTemp.RecordCount = 0 then
	'如果沒有資料，傳回空的Recordset XML資料
    strXML = strXML & "<Recordset CurrentPage='0' TotalPage='0'>" & vbcrlf
else
	'進行資料的分頁
    rstTemp.PageSize = intPageSize
    if clng(lngPage) <= clng(rstTemp.PageCount) then
        rstTemp.AbsolutePage = clng(lngPage)
    else
        rstTemp.AbsolutePage = rstTemp.PageCount
    end if
    '產生 Recordset的表頭
    strXML = strXML & "<Recordset CurrentPage='" & rstTemp.AbsolutePage & "' TotalPage='" & rstTemp.PageCount & "'>" & vbcrlf

	'逐筆產生Recordset裡面的每一筆Record
	dim i,j
    for i = 1 to rstTemp.PageSize
        if rstTemp.EOF = true then
            exit for
        end if
        '產生Record表頭
        strXML = strXML & "<Record id='" & i & "'>" & vbcrlf
        '產生每一個欄位的資料
        for j = 0 to rstTemp.Fields.Count - 1
            strXML = strXML & "<fld" & j+1 & ">" & sys_XMLEncode(rstTemp.Fields(j).value) & "</fld" & j+1 & ">" & vbcrlf
        next
        strXML = strXML & "</Record>" & vbcrlf
        '移動到下一筆
        rstTemp.MoveNext
    next
end if

strXML = strXML & "</Recordset>" & vbcrlf
strXML = strXML & "</Data>" & vbcrlf

EOF
}

ws_list_response() {
cat <<EOF
'設定資料的型態為 text/xml
Response.ContentType = "text/xml"
Response.Write strXML
%>
EOF
}

_ws_ListTemplate_S_asp() {
    ws_list_header
    ws_list_page_size
    ws_list_SQL
    ws_list_XML
    ws_list_response
}    
